intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{mini_chromium}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DMINI_CHROMIUM_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DMINI_CHROMIUM_SHARED_BUILD

# Export options.
#
lib{mini_chromium}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{mini_chromium}: cxx.export.poptions += -DMINI_CHROMIUM_STATIC
libs{mini_chromium}: cxx.export.poptions += -DMINI_CHROMIUM_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{mini_chromium}: bin.lib.version = "-$version.project_id"
else
  lib{mini_chromium}: bin.lib.version = "-$version.major.$version.minor"

# Install into the mini_chromium/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/mini_chromium/
  install.subdirs = true
}
